# Generated by Django 3.1.3 on 2022-10-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('al_name', models.CharField(max_length=200)),
                ('al_branch', models.CharField(max_length=200)),
                ('al_git_url', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200)),
                ('dataset_description', models.TextField()),
                ('dataset_type', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainDatasetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_image_path', models.CharField(max_length=1000)),
                ('ds_image_name', models.CharField(max_length=200)),
                ('ds_image_class_num', models.CharField(max_length=50)),
                ('ds_image_class_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ds_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gan_dm.traindataset')),
            ],
        ),
        migrations.CreateModel(
            name='GenerateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('model_path', models.CharField(max_length=1000)),
                ('model_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('algorithm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gan_dm.algorithm')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ds_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gan_dm.traindataset')),
            ],
        ),
    ]
