# Generated by Django 3.1.3 on 2022-10-20 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gan_dm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenerateModel',
            new_name='GenerativeModel',
        ),
    ]
