# Generated by Django 3.1.3 on 2022-10-28 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gan_dm', '0002_auto_20221021_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputInferenceDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ii_dataset_name', models.CharField(max_length=200)),
                ('ii_dataset_description', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_dataset_name', models.CharField(max_length=200)),
                ('res_dataset_description', models.TextField()),
                ('res_dataset_count', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultDatasetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_ds_image_path', models.CharField(max_length=1000)),
                ('res_ds_image_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('res_ds_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gan_dm.resultdataset')),
            ],
        ),
        migrations.CreateModel(
            name='InputInferenceDatasetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ii_ds_image_path', models.CharField(max_length=1000)),
                ('ii_ds_image_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ii_ds_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gan_dm.inputinferencedataset')),
            ],
        ),
    ]
